### ISSUE TITLE
能简要描述一下工程吗

### ISSUE THREAD

**Issue by xrfinbupt** [klose911/payment#11]
设计思路以及使用场景，解决的问题能说一下 吗

**Comment by klose911** [comment]
主要目的是实现一个单独部署的支付网关，用于和支付宝，微信JS，快钱等第三方支付进行集成

设计思路主要是

t_payment_ext_conf表用于保存客户化的prepay callback的spring bean名称
t_payment_account表用于保存支付账户的配置信息
t_payment_transaction表用于保存每笔订单的实例信息

1. 在数据库配置支付帐号相关信息
2. 根据商品订单信息，产生html表单
3  通过http或者https发送给各大支付平台
4  页面跳转到各大支付平台进行支付
5  支付完成支持前台和后台回调
6  前台回调主要用于展示支付结果
7  后台回调主要用于交易完成

流程：

testPay.jsp是主入口，调用org.klose.payment.server.rest.PaymentResource#createPayment这个restful接口
1. 从订单信息OrderDto产生支付信息BillingData,
2. org.klose.payment.api.PaymentProxy#createPayment
根据不同的账户类型调用不同的服务类，比如org.klose.payment.integration.alipay.AlipayPaymentService
3. 这些service会根据已经不同的支付网关的协议，产生相应要发送的支付表单PaymentForm
，其中最重要的工作是对表单进行签名，前台，后台回调地址往往都会包含在这份表单的参数内
4. 支付表单会被发送到paymentForm.jsp, 提交后，发送给第三方支付
5
 不同的第三方支付有不同的回调实现，比如org.klose.payment.integration.alipay.AliPayNotificationResource
接受回调后，主要是先进行签名验证，判断支付状态，回调response记录，如果一切顺利完成交易
6  前台回调只是有一个简单的默认实现paymentResult.jsp, 这个可以项目上自己实现


客户化：

实现'org.klose.payment.server.prepare.PaymentIntegrationService'，
准备商品，价格，订单等各种信息

实现'org.klose.payment.api.CallBackAgent' 后台回调的“完成交易”部分在这里实现

Cheers and Good Luck
Klose

2016-08-14 23:58 GMT+08:00 xrfinbj <notifications@github.com>:

**Comment by klose911** [comment]
项目简介，设计思路等参考更新后的README.md.
